jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.1
      - run: dotnet build

  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.1
      - run: dotnet test -p:CollectCoverage=true

  analyze:
    needs: [build, test]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.1
      - run: dotnet tool install --global dotnet-sonarscanner
      - run: | 
          dotnet sonarscanner begin -o:'devjamesc' -k:'DevJamesC_DevopsCI-Training' -d:sonar.login='d0e4d458e7b4cf5dc09ec7867b6b2e1be388bd8f' -d:sonar.host.url='https://sonarcloud.io/'
          dotnet build
          dotnet test -p:CollectCoverage=true
          dotnet sonarscanner end -d:sonar.login='d0e4d458e7b4cf5dc09ec7867b6b2e1be388bd8f'
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # package:
  # deploy:

name: cibuild

on: push




# person:
#   firstname: 'string' # string
#   lastname: 100 # number
#   middlename: true #boolean
#   alias: # - denotes a collections
#     - 'dotnet'
#     - 'lead'
#     - 'burns'